version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_store
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"
    volumes:
      - "~/postgres_data:/var/lib/postgresql/data"
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: maxdn@mail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
  